name: Cypress.io Tests

on: 
  push:
    branches:
      -main 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - run: npm ci
      - run: npm test
      - run: npm run build
    
    
